name: continuous auto-formatting

on: [pull_request, push]

jobs:
  get_input:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.abc.outputs.value }}

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print modified files
        shell: bash
        run: |
          file=${{ steps.abc.outputs.all }}
          echo "$file" > modified.txt
          cat modified.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: committed_filenames
          path: modified.txt

  autopep8_format:
    #Checks if PR is not from a fork. Avoids Action failure because if PR comes from another repo, it cannot access repo secret.
    #if: github.event.pull_request.head.repo.full_name == github.repository
    needs: get_input
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      Modified: ${{steps.fuck.outputs.modified_files}}

    steps:
      - run: echo "An auto-formatting action is being triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: committed_filenames
          path: modified.txt

      - name: Print Modified Files
        id: fuck
        shell: bash
        run: |
          value='cat modified.txt/modified.txt'
          echo "::set-output name=modified_files::$value"
          echo $value

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Prereqs
        id: command_line_outputs
        run: |
          python -m pip install --upgrade pip
          pip install autopep8
          cd ${{ github.workspace }}

      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          fail-on-error: false
          script: |
            import autopep8
            import os
            print(os.environ['Modified'])
            for root, _, files in os.walk(os.getcwd()):
              path = root + os.path.sep
              for file in files:
                if file.endswith(".py"):
                  texts = []
                  with open(os.path.join(path, file), mode='r', encoding='UTF-8') as f1:
                    texts = f1.read()
                  with open(os.path.join(path, file), mode='w', encoding='UTF-8') as f2:
                    texts = autopep8.fix_code(texts)
                    f2.write(f'{texts}\n')

      - name: Print errors
        if: steps.script.outputs.error == 'true'
        run: |
          printenv "SCRIPT_STDOUT"
          printenv "SCRIPT_STDERR"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
          SCRIPT_STDERR: ${{ steps.script.outputs.stderr }}

      - name: Check Modified Files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)

      - name: Push Change
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Beckham Pan' 
          git config --global user.email 'beckham.0831@yahoo.com.tw' 
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}
          git commit -a -m "Automated (PEP8 Formatting) changes" 
          git push

      - name: All Good
        # Consider case where no file formatting is needed
        if: steps.git-check.outputs.modified == 'false'
        run: echo "No code formatting needed. You write Python in perfect format :)"
