# Before enabling this workflow, configure the following settings:
# 1. On GitHub.com, navigate to the main page of the repository.
# 2. Under your repository name, click "Settings"
# 3. In the left sidebar, click "Actions", and select "General" upon the slide-down menu
# 4. Scroll down to "Workflow Permissions", and select "Read and Write Permissions".
# 5. Tick the "Allow GitHub Actions to create and approve pull requests" box and press "Save".

# To grant additional permissions/accesses, a customized Token can be generated and added to the repo secret.
# For more info, visit https://docs.github.com/en/actions/security-guides/automatic-token-authentication

# IMPORTANT: Pulls that are requested by forked repos would trigger a FAILED Action,
# for PRs coming from other repos cannot access local repo secrets.

name: continuous auto-formatting

on: [pull_request]

jobs:
  autopep8_format:
    #Checks if PR is not from a fork. Avoids Action failure because if PR comes from another repo, it cannot access repo secret.
    #if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - run: echo "An auto-formatting action is being triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Prereqs
        id: command_line_outputs
        run: |
          python -m pip install --upgrade pip
          pip install autopep8
          cd ${{ github.workspace }}

      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          fail-on-error: false
          script: |
            import autopep8
            import os

            for root, _, files in os.walk(os.getcwd()):
              path = root + os.path.sep
              for file in files:
                if file.endswith(".py"):
                  texts = []
                  with open(os.path.join(path, file), mode='r', encoding='UTF-8') as f1:
                    texts = f1.read()
                  with open(os.path.join(path, file), mode='w', encoding='UTF-8') as f2:
                    texts = autopep8.fix_code(texts)
                    f2.write(f'{texts}\n')

      - name: Print errors
        if: steps.script.outputs.error == 'true'
        run: |
          printenv "SCRIPT_STDOUT"
          printenv "SCRIPT_STDERR"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
          SCRIPT_STDERR: ${{ steps.script.outputs.stderr }}

      - name: Check Modified Files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push Change
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Beckham Pan' 
          git config --global user.email 'beckham.0831@yahoo.com.tw' 
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }} 
          git commit -a -m "Automated (PEP8 Formatting) changes" 
          git push

      - name: All Good
        # Consider case where no file formatting is needed
        if: steps.git-check.outputs.modified == 'false'
        run: echo "No code formatting needed. You write Python in perfect format :)"

  # check job1 status. If not successfull, do something.
  # check_job:
  #   needs: autopep8_format
  #   runs-on: ubuntu-latest
  #   if: needs.autopep8_format.result == "skipped" || needs.autopep8_format.result == "failure"
  #   steps:
